extension: csv # Can be csv or json
names_filepath: data/csv/names.csv
token_count_file: data/json/partitioned_files/andrew_paul.json
processing_json_file: data/json/s_m718trl32gq7jdo2ld_pretty.json
partition_input_file: data/json/full_json_list_pretty.json
nlp_processing_file: data/json/test_files/abraham_hazim.json
processing_folder: data/json/partitioned_files
db_filepath: data/db/profiles.db
schema_filepath: schema.yml
limit: 1000